version: '3'

services:

  caddy:
    ports:
      - 80:8080
      - 9487:8081
    volumes:
      - ./.config/Caddyfile:/etc/Caddyfile

  vue:
    volumes:
      - ./Front-End:/app
      - /app/node_modules/

  web:
    volumes:
      - ./Back-End:/app

  robot:
    volumes: 
      - ./Course-Taking:/app
